package raiderInventories;

import raiderInventories.InventoryManager;

public class demoAddDecrement {
	
	public static void main(String[] args) {
		System.out.println("-In this demo lines that begin with a dash \"-\" explain the demo.\n"
				+ "-Any other lines are generated by the system.\n"
				+ "-Let's create Refrigerators \"Kitchen\", \"Pool House\"\n"
				+ "-and ShoppingList \"Market List\".\n");
		
		InventoryManager InvMaster = InventoryManager.getInstance();
		
		RaiderInventory kitchen = InvMaster.addInventory("Kitchen", 02, "Refrigerator");
		//Refrigerator poolHouse = new Refrigerator(InvMaster, "Pool House");
		//ShoppingList marketList = new ShoppingList(InvMaster, "Market List");
		
		
		System.out.println("\n-Is the Kitchen:Refrigerator empty?\n");
		kitchen.isEmpty();
		
		System.out.println("\n- Let's add Chedder Cheese 2, Milk 1, and try to add Butter, -2");
		kitchen.addItem("Chedder Cheese", 2, "Dairy");
		kitchen.addItem("Milk", 1, "Dairy");
		kitchen.addItem("Butter", -2, "Dairy");
		kitchen.addItem("Steak", 0, "Meat");
		
		System.out.println("\n-Is the Kitchen Refrigerator still empty?");
		kitchen.isEmpty();
		
		kitchen.printContents();
		
		System.out.println("-Lets Increment Milk.");
		kitchen.incrementItem("milk");
		
		kitchen.printContents();
		
		kitchen.printOOS();
		
	}
}
